//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabelMeta {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BabelMeta.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog not present..
        /// </summary>
        internal static string MainFormFugaToolStripMenuItem_Click_CatalogNotPresent {
            get {
                return ResourceManager.GetString("MainFormFugaToolStripMenuItem_Click_CatalogNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a root folder for output sub-folders and XML files..
        /// </summary>
        internal static string MainFormFugaToolStripMenuItem_Click_FolderBrowserDialog {
            get {
                return ResourceManager.GetString("MainFormFugaToolStripMenuItem_Click_FolderBrowserDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a root folder to load session files..
        /// </summary>
        internal static string MainFormloadSessionToolStripMenuItem_Click_SelectRootFolder {
            get {
                return ResourceManager.GetString("MainFormloadSessionToolStripMenuItem_Click_SelectRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a root folder to save session files..
        /// </summary>
        internal static string MainFormSaveSessionToolStripMenuItem_Click_SelectRootFolder {
            get {
                return ResourceManager.GetString("MainFormSaveSessionToolStripMenuItem_Click_SelectRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not saved: I/O error on disk..
        /// </summary>
        internal static string MainFormSaveSessionToolStripMenuItem_Click_SessionNotSaved {
            get {
                return ResourceManager.GetString("MainFormSaveSessionToolStripMenuItem_Click_SessionNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string MainFormTemplatedWorkbookToolStripMenuItem_Click_AllFiles {
            get {
                return ResourceManager.GetString("MainFormTemplatedWorkbookToolStripMenuItem_Click_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xls, *.xlsx)|*.xls*.
        /// </summary>
        internal static string MainFormTemplatedWorkbookToolStripMenuItem_Click_ExcelFiles {
            get {
                return ResourceManager.GetString("MainFormTemplatedWorkbookToolStripMenuItem_Click_ExcelFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input format selected..
        /// </summary>
        internal static string MainFormTemplatedWorkbookToolStripMenuItem_Click_NoInputFormatSelected {
            get {
                return ResourceManager.GetString("MainFormTemplatedWorkbookToolStripMenuItem_Click_NoInputFormatSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a default file.
        /// </summary>
        internal static string MainFormTemplatedWorkbookToolStripMenuItem_Click_OpenDefaultFile {
            get {
                return ResourceManager.GetString("MainFormTemplatedWorkbookToolStripMenuItem_Click_OpenDefaultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string MainFormTemplatedWorkbookToolStripMenuItem_Click_XmlFiles {
            get {
                return ResourceManager.GetString("MainFormTemplatedWorkbookToolStripMenuItem_Click_XmlFiles", resourceCulture);
            }
        }
    }
}
